export const glossaryTerms: Record<string, string> = {
  'Blockchain': 'A digital record-keeping system stored across many computers, making it secure and tamper-proof',
  'blockchain': 'A digital record-keeping system stored across many computers, making it secure and tamper-proof',
  'Memecoins': 'Cryptocurrencies created as jokes or internet trends with little real-world utility',
  'memecoins': 'Cryptocurrencies created as jokes or internet trends with little real-world utility',
  'Speculation': 'Buying assets hoping they\'ll rise in value rather than using them practically',
  'speculation': 'Buying assets hoping they\'ll rise in value rather than using them practically',
  'Transaction fees': 'Small costs paid to process and confirm actions on a blockchain network',
  'transaction fees': 'Small costs paid to process and confirm actions on a blockchain network',
  'Micro-payments': 'Tiny payments, often fractions of a cent, made possible by low-fee networks',
  'micro-payments': 'Tiny payments, often fractions of a cent, made possible by low-fee networks',
  'Decentralized': 'Not controlled by any single company, government, or person',
  'decentralized': 'Not controlled by any single company, government, or person',
  'Firedancer': 'Solana\'s next-generation upgrade designed to dramatically increase network speed',
  'Firedancer': 'Solana\'s next-generation upgrade designed to dramatically increase network speed',
  'Composability': 'The ability of different apps on a network to connect and work together seamlessly',
  'composability': 'The ability of different apps on a network to connect and work together seamlessly',
  'Ecosystem': 'A community of interconnected projects, apps, and users built around one platform',
  'ecosystem': 'A community of interconnected projects, apps, and users built around one platform',
  'Unbanked': 'People without access to traditional banking services like savings accounts or credit',
  'unbanked': 'People without access to traditional banking services like savings accounts or credit',
  'DePIN': 'Decentralized Physical Infrastructure Network — real-world infrastructure owned by a community',
  'HONEY tokens': 'The cryptocurrency earned by Hivemapper contributors for mapping roads',
  'HONEY': 'The cryptocurrency earned by Hivemapper contributors for mapping roads',
  'On-chain': 'Data recorded directly on the blockchain, publicly and permanently',
  'on-chain': 'Data recorded directly on the blockchain, publicly and permanently',
  'Extractive model': 'A business model where a company takes user data without fairly compensating them',
  'Ethereum': 'An older blockchain network known for slower speeds and higher fees than Solana',
  'ethereum': 'An older blockchain network known for slower speeds and higher fees than Solana',
  'Pantera Capital': 'A major cryptocurrency-focused investment firm',
  'Mapbox': 'A platform providing location data and mapping services to developers',
  'Robotaxi': 'A self-driving taxi that operates without a human driver',
  'robotaxi': 'A self-driving taxi that operates without a human driver',
  'Scalability': 'A network\'s ability to handle more users without slowing down or getting expensive',
  'scalability': 'A network\'s ability to handle more users without slowing down or getting expensive',
  'Infrastructure': 'The underlying systems that other services and applications are built on top of',
  'infrastructure': 'The underlying systems that other services and applications are built on top of',
  'blockchain network': 'A digital record-keeping system stored across many computers, making it secure and tamper-proof',
  'Stablecoin': 'A cryptocurrency designed to maintain a stable value, typically pegged to a fiat currency like the US dollar',
  'stablecoin': 'A cryptocurrency designed to maintain a stable value, typically pegged to a fiat currency like the US dollar',
  'Finality': 'The point at which a transaction is permanently recorded and cannot be reversed or undone',
  'finality': 'The point at which a transaction is permanently recorded and cannot be reversed or undone',
  'remittances': 'Money sent by workers to their home countries, often to support families',
  'Remittances': 'Money sent by workers to their home countries, often to support families',
}
